version: '3.8'

services:
  app:
    image: emilykamiti/resale
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - database

  database:
    image: mysql:latest
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: nasinza2891
      MYSQL_DATABASE: resale