--
- name: ResaleAuctionSystem deployment
  hosts: all
  become: true
  tasks:
    - name: Recursively change ownership
      file:
        path: /home/emily/Resale/
        state: directory
        recurse: yes
        owner: emily
      become: true

    - name: Copy Docker Compose File
      copy:
        src: ./docker-compose.yml
        dest: /home/emily/Resale/docker-compose.yml

    - name: Run Docker Container
      command: docker-compose -f /home/emily/Resale/docker-compose.yml up -d